# Generated by Django 2.2.6 on 2019-10-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stations', to='stations.Zone'),
            preserve_default=False,
        ),
    ]
