# Generated by Django 2.2.6 on 2019-10-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_lines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lines',
            new_name='Line',
        ),
    ]
